// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_YDdM61YdA1YynDZLJ4uvyo1IYG0GPfQ',
    appId: '1:900349856495:web:63077f69f64d31d20fe91a',
    messagingSenderId: '900349856495',
    projectId: 'cbsee-1f435',
    authDomain: 'cbsee-1f435.firebaseapp.com',
    storageBucket: 'cbsee-1f435.firebasestorage.app',
    measurementId: 'G-XZL0LWY7FD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdQrLKESk6R25brZNxrmNTNA2rUyOAtu8',
    appId: '1:900349856495:android:bfffed3cbf6d26c10fe91a',
    messagingSenderId: '900349856495',
    projectId: 'cbsee-1f435',
    storageBucket: 'cbsee-1f435.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD6ehqyIJRnREA7fJzI9N-hrBbiV6I_ok',
    appId: '1:900349856495:ios:ba332f8bccbe886d0fe91a',
    messagingSenderId: '900349856495',
    projectId: 'cbsee-1f435',
    storageBucket: 'cbsee-1f435.firebasestorage.app',
    iosClientId: '900349856495-to9ac54orlj2ie0dlrhu3fmg3me6rgi3.apps.googleusercontent.com',
    iosBundleId: 'com.example.cbseeFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD6ehqyIJRnREA7fJzI9N-hrBbiV6I_ok',
    appId: '1:900349856495:ios:ba332f8bccbe886d0fe91a',
    messagingSenderId: '900349856495',
    projectId: 'cbsee-1f435',
    storageBucket: 'cbsee-1f435.firebasestorage.app',
    iosClientId: '900349856495-to9ac54orlj2ie0dlrhu3fmg3me6rgi3.apps.googleusercontent.com',
    iosBundleId: 'com.example.cbseeFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_YDdM61YdA1YynDZLJ4uvyo1IYG0GPfQ',
    appId: '1:900349856495:web:d7ba6ab48dca47200fe91a',
    messagingSenderId: '900349856495',
    projectId: 'cbsee-1f435',
    authDomain: 'cbsee-1f435.firebaseapp.com',
    storageBucket: 'cbsee-1f435.firebasestorage.app',
    measurementId: 'G-BPFBXPHEM3',
  );
}
