import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file is generated by the FlutterFire CLI

import 'auth_gate.dart';
import 'screens/login_screen.dart';
import 'screens/signup_screen.dart';
import 'screens/scan_screen.dart';
import 'screens/history_screen.dart';
import 'screens/settings_screen.dart';
import 'screens/discoveries_screen.dart';
import 'screens/teacher_dashboard_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'CBSee App',
      theme: ThemeData(
        primarySwatch: Colors.green,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      // AuthGate is now the main entry point for your app's UI
      home: const AuthGate(), 
      routes: {
        // These routes are still useful for navigation *after* login
        '/login': (context) => const LoginScreen(),
        '/signup': (context) => const SignupScreen(),
        '/scan': (context) => const ScanScreen(),
        '/history': (context) => const HistoryScreen(),
        '/settings': (context) => const SettingsScreen(),
        '/dashboard': (context) => const DiscoveriesScreen(),
        '/teacher_dashboard':(context) => const MyClassroomScreen(),
        // The following routes are now obsolete and can be removed:
        // '/verify': (context) => const VerifyAccountScreen(),
        // '/teacher_signup': (context) => const TeacherSignupScreen(),
        // '/teacher_login':(context)=>const TeacherLoginScreen(),
      },
      debugShowCheckedModeBanner: false,
    );
  }
}