import 'package:cbsee_frontend/screens/discoveries_screen.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file is generated by the FlutterFire CLI
import 'screens/login_screen.dart';
import 'screens/signup_screen.dart';
import 'screens/verify_account_screen.dart';
import 'screens/teacher_signup_screen.dart';
import 'screens/scan_screen.dart';
import 'screens/history_screen.dart';
import 'screens/settings_screen.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  try {
    if (Firebase.apps.isEmpty) {
 

// ...

    await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
    );
    }
  } catch (e) {
    debugPrint('Firebase initialization failed: $e');
  }
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'CBSee App',
      theme: ThemeData(
        primarySwatch: Colors.green,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      initialRoute: '/login', // Set the initial route
      routes: {
        '/login': (context) => const LoginScreen(),
        '/signup': (context) => const SignupScreen(),
        '/verify': (context) => const VerifyAccountScreen(),
        '/teacher_signup': (context) => const TeacherSignupScreen(),
        '/scan': (context) => const ScanScreen(),
        '/history': (context) => const HistoryScreen(),
        '/settings': (context) => const SettingsScreen(),
        '/dashboard': (context) => const DiscoveriesScreen()
        // Define other routes as needed
      },
      debugShowCheckedModeBanner: false,
    );
  }
}