# Generated by Django 5.0.6 on 2025-10-05 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('ParentID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('ContactInfo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('DateOfBirth', models.DateTimeField(auto_now_add=True)),
                ('GradeLevel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('School', models.CharField(max_length=100)),
                ('ContactInfo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('ReportID', models.AutoField(primary_key=True, serialize=False)),
                ('DateGenerated', models.DateTimeField(auto_now_add=True)),
                ('Summary', models.CharField(max_length=255)),
                ('Recommendations', models.CharField(max_length=255)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectRecognized',
            fields=[
                ('ObjectID', models.AutoField(primary_key=True, serialize=False)),
                ('ObjectName', models.CharField(max_length=100)),
                ('ObjectDescription', models.CharField(max_length=255)),
                ('RecognitionAccuracy', models.FloatField()),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognized_objects', to='api.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.teacher'),
        ),
    ]
