# Generated by Django 5.0.2 on 2025-10-12 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('ObjectID', models.AutoField(primary_key=True, serialize=False)),
                ('ObjectName', models.CharField(max_length=100)),
                ('ObjectDescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='objectrecognized',
            old_name='ObjectID',
            new_name='ID',
        ),
        migrations.RemoveField(
            model_name='objectrecognized',
            name='ObjectDescription',
        ),
        migrations.RemoveField(
            model_name='objectrecognized',
            name='ObjectName',
        ),
        migrations.RemoveField(
            model_name='objectrecognized',
            name='RecognitionAccuracy',
        ),
        migrations.AddField(
            model_name='objectrecognized',
            name='Object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognized_instances', to='api.object'),
        ),
    ]
