# Generated by Django 5.0.2 on 2025-10-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_object_rename_objectid_objectrecognized_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': 'Object', 'verbose_name_plural': 'Objects'},
        ),
        migrations.AddField(
            model_name='object',
            name='ObjectCategory',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
