# Generated by Django 5.0.2 on 2025-10-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_object_options_object_objectcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectrecognized',
            name='Timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time this object was recognized.', null=True),
        ),
    ]
