# Generated by Django 5.2.7 on 2025-10-20 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_objectrecognized_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='api.teacher'),
        ),
    ]
