# Generated by Django 5.2.7 on 2025-10-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
