# Generated by Django 5.2.7 on 2025-10-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='GradeLevel',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
