# Generated by Django 5.0.2 on 2025-10-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_teacher_gradelevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
    ]
